### ISSUE TITLE
What is the difference between the dash-t TCGA expected counts files and the non-dash-t TCGA expected counts files in

### ISSUE THREAD

**Issue by nellore** [mskcc/RNAseqDB#4]
https://github.com/mskcc/RNAseqDB/tree/master/data/expected_count ?

Thanks!
A

**Comment by qwangmsk** [comment]
dash-t TCGA are tumor samples and non-dash-t are adjacent normals.

**Comment by nellore** [comment]
Thanks!

**Comment by y9c** [comment]
@qwangmsk  Can you add it to readme file? I can't found any comment  about this in both the paper and the code.
